# Generated by Django 2.1.2 on 2018-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0002_auto_20181023_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bodybuild',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='bodysim',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='bodyweight',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='displaymultitouch',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='displayprotection',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='displayresolution',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='displaysize',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='displaytype',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='internalmemory',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='maincameradual',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='maincamerafeatures',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='maincameravideo',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='memorycardslot',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='platformchipset',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='platformcpu',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='platformgpu',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='platformos',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=60, null=True),
        ),
    ]
