# Generated by Django 2.1.2 on 2018-10-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0005_auto_20181026_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='PhoneArticle',
        ),
    ]
