# Generated by Django 2.1.2 on 2018-10-30 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0007_phonearticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonearticle',
            name='audiotest',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='battery',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='batterytest',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='bodybuild',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='bodydimensions',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='bodysim',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='bodyweight',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='cameratest',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commsbluetooth',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commsgps',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commsnfc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commsradio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commsusb',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='commswlan',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='devicecolors',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaymultitouch',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displayprotection',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displayresolution',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaysize',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaytest',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaytype',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='featuresbrowser',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='featuresmessaging',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='featuressensors',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='gprsandedge',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='internalmemory',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='launchannounced',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='launchavailable',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='loudspeakertest',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincameradual',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincamerafeatures',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincameravideo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='memorycardslot',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='network2G',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='network3G',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='network4G',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='otherfeatures',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='performancetests',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformchipset',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformcpu',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformgpu',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformos',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='priceinkenya',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='priceinnigeria',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='priceinsouthafrica',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='selfiecameradual',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='selfiecamerafeatures',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='selfiecameravideo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='soundalerttypes',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='soundheadphonejack',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='soundloudspeaker',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
    ]
