# Generated by Django 2.1.2 on 2018-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0009_auto_20181031_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonearticle',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
