# Generated by Django 2.1.2 on 2018-10-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('News', '0002_auto_20181019_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('articleUrl', models.CharField(max_length=120)),
                ('imageUrl', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=60)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='News.tags'),
        ),
    ]
