# Generated by Django 2.1.2 on 2018-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20181025_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonearticle',
            name='bodyweight',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
