# Generated by Django 2.1.2 on 2018-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20181025_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonearticle',
            name='bodybuild',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='bodysim',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaymultitouch',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displayprotection',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displayresolution',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaysize',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='displaytype',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='internalmemory',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincameradual',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincamerafeatures',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='maincameravideo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='memorycardslot',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='phonesimages/'),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformchipset',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformcpu',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformgpu',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='phonearticle',
            name='platformos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
