# Generated by Django 2.1.2 on 2018-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20181025_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonearticle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
