# Generated by Django 2.1.2 on 2018-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_phonearticle_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
