# Generated by Django 2.1.2 on 2018-10-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_newsarticle_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonearticle',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PhoneArticle',
        ),
    ]
