# Generated by Django 2.1.2 on 2018-10-29 13:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20181027_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
